language: node_js
node_js: 7
script:
  - yarn run build
  - yarn run lint
  - yarn run flow -- check --show-all-errors
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  yarn: true
env:
  global:
    # CHROME_CLIENT_ID
    - secure: bZHChjt/klasnBPm4Jqy8TqV14lB1FF0XnEWyEwxmtUvwiGIhpDyCZ0CBcPxAbtMrMBX8dUrobnlyu+a3lpzicK2tsLwOGFaiOV+OB6B94Nql+Ois8NZuUWh2RNaxnYdH64Qd/b/WLgIFK4ElVUxycCIemDE3kVgMGNgHr3CwS/rDUiyuYVifTAF+212si5fXr9wzRYkg5/4SvRShYMNB5VeYawWqWzmXDc0ZCBmtmLcUvRHaAPGZnicKbxq+3DYs5Mx6WjRMQ4TQ7oxq9SeQQoSXozFSL+NLDYq2KVCi7NbwRWvVkPWzuDUfJ9dkLh9Mohm2in6/uwlZPruxeaqbMzSTGzXTfGe+pjQjOpp4JE9ReltPwtBOiJnqcbROE6rtY7N5ts15Vuu+yVfSyhvLW+Dlvv4dd2hK0XxmE44gE8zM5Y224yxH4/Et3DyiV+U4OKwMLMBRnh8hz/6zlvFtStKHjJXCPBj0021sqc+Bt86F9QZ3jFETPYW4Nf6vbnCbBR7WuvIBDWJN1iLBkqURnVOoV3KwPcLEA2yoBdChyhC2jGK0FPezrDwpqb2zEaLnM7dRakrHumDvlTWSOcCJ66hN9cRbER4UjF0pHwbj5baCh1KusJkRAxVvFWv59VidTli9kzxcwKulNtPQHf632ZycyAWVNsps7mFZQEZWD0=
    # CHROME_CLIENT_SECRET
    - secure: VC4lSViUSlqqeNXW+J2ByI+w+pITND/v12Ehrj0ZT0UYl2BmN1XTb+Mnh9yVnVoCRmsZ+8mPw7NmOCRsX79fKWcyj9zSiVZhxUE6vIc7cC2/ZLz4vVH/fjXosquZgP75AOv1Lg9e8U2ZKW+lOPUrTjGB3O/d2h28isJj+KX1J0gUFemb6wWI3G8xxptztvwXY5d+KtI+b4Z4nX6srN/rnXfmsX7r+hl+1VSX2231hS2UqgqNGV9NNJ7+RdXEDOR/gQmIQLks65eb8zun1vOuuatDFA4BDz39vQNaMl/Tx4E7GFKx/H2WiF00rsfB40g8i/sO3HG5OBeSXwtYTZd/I/deIwvCnJvKdFyamM93pDywiFvzy50XK1T5s3EZ97FcHoPHgSWm2NUj8a9gVg5HV+h2OBw+UImrueE6/WJ4jgflOVJHHnzSbOPILBgj8M9Zr8cyunheknOrGsUPi7ZQZ8TY0nWBt8TY6L9de9MZbRqdukIgQGQhmYzxXXhssgwCSbuIembOIphTPOL+pnAqC6cTWobD3hkn1Gp6HzX/eo0JXAUAP9EloYQJEHjH7j5kQyZVH83A6EPQKpy77o5WL9lwvbZHkBU/5Sh5ytwrcsNUCuWx04egXNtPr4Xn9JjIPKggUCbdhoe8cacWGzKX7EvB00wyffr69BJCWNXotrc=
    # CHROME_REFRESH_TOKEN
    - secure: YyuOZX19DC5RrI5tOX6v7TECC22ZJD8VzkSLXXixatV51QR1r3uVHCWchDeVD0rW6A/6AvvCvUzbI5LcRSX/cWiXXfdqBUyEbsXqYvnujFGBBH2olvGBftPvKUsqQOE07Ma0I/hRGAKv6qjWXzqjx8w2x8c3XT/xOSxavIA5kAytYcFaaycnxnHe23NxYiiuEe22Acr/iV5DjjybOmw1jDugLSAWMkS5nveOdkhVjnrsqIZqf5sEJCo2FQou1H1lK/DTkocFxTYOplCJfCMlig7nUcsKZRxldqPUuVUzXa1vNmulJQNG7g43hQMZzDqLyVYgyNAvc2Ii7wc+Ct4Quc50YtFzjTDtfLczFniQoW5N8QWFILudoJOGQX3IKssv+O3n1CilNAWahz3AFWuqyxnNpSGCrOxyH/E4V0DmV05JXj4jGhZh/xuuy7e0eNrWB2N+aWI9anzY1TYB7tZ4pdUx1gNJ+EtFSKOjx5vTMHFdXaCxaX2XtZLsqM+6lk0e9VBF+V7iuSyRc1mM1R2KD3ER/6B6HQfgnQqpmZIg1qAaY6hXqkG8hrEZHGR9N9kNIye/Ouxp1sCPgGY7WFsg3ec9HzazqOAN8w6RlzYLI2j9kvLP2stnNmWfvUV/fzFXakTV/OnX1n7XYZuFc7xBi28ImyhvCpdbTia5DbcdiOI=
deploy:
  - provider: script
    script: node deploy.js
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key:
      secure: kBbj3H2bs80+g3GBhRrat/X1oE+Dg0avFB2IfecIZJWKjfQQEVedXuTD/2/K9xtnDAaWOdW56FPVKIEerJ2GWNMsrazIW1KD3pq7H14GnWLHKxNUk1OUdTjhHFs3Gyuxd2JK3JRo1zyYNi4zdhrYNOvLuiW/Wcy4rpxvnglgBnRBuX7AjQznd7W+u3bGczqlT5DjfA0Is7e1wWsEzHhsjs33RgIvD7KmsDrew5nzc8hGaS1X4b81bU4mSe6NIKstigqBgf9/zRJeN7XuuxOAYqzfeLG02RL+ucOffuflNkxR6ykvJeJvzVlLewzLI/KEZ9dhY0NakDhVOKXd9+JJvwLbdwgDErDXpxe174hjZd5axB2ba5fE1IDwqVTeUZF3YwhcyqpfjFslbn1RBPuXaV1Mb5Kf0Qo/cLKZ9G2hHUeaFdvoicZ1yZ/CNDqWJ+lb/dVVIvSyQfaQYOKuf0wbnm/i+9sO38OJ3WzyHbS74Q+Hfd+4O92w5gjztUOBfUGiMruV+9yIUtlhAFJYEvhaheOoV0UxVsFipqFHEbLoExHehu+edfyL5KfUFAo0sQnOKQPgAc2xRjLRz9ioZRA4yq3z3ZtycG2VaKXARtEWMaKb86w28I9liCsZp8cCV7nEKSpb5K3cWbtsrzMUOP6V80MUgchOlyP7Ey7JtTVMtb8=
    file: dist/BTD2X.zip
    skip_cleanup: true
    on:
      tags: true
